
#Client only settings, mostly things related to rendering
[client]
	#The corner for the Curios GUI button
	#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
	buttonCorner = "TOP_LEFT"
	#The X-Offset for the Curios GUI button
	#Range: -100 ~ 100
	buttonXOffset = 0
	#Set to true to enable rendering curios
	renderCurios = true
	#The Y-Offset for the Curios GUI button
	#Range: -100 ~ 100
	buttonYOffset = 0

